name: Rector

on: [ push ]

jobs:
    rector:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ '7.4' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@2.16.0
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
                    extensions: ast

            -   name: Install Composer deps
                uses: ramsey/composer-install@v2
                with:
                    composer-options: --no-scripts

            -   name: Install Composer bin PHPUnit
                uses: ramsey/composer-install@v2
                with:
                    working-directory: './vendor-bin/phpunit'

            -   name: Run Rector
                run: |
                    ./vendor/bin/rector process --dry-run
